config/routes.rb
WebJzcnw::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'home/index'
  get 'home/publish'
  match '/publish/:type' => 'home#publish', :via => :get
  match '/publish/:type/add' => 'home#add', :via => :get, :as => :home_publish_add
  match '/records/create' => 'home#create', :via => :post, :as => :home_records
  match '/records/:id' => 'home#show', :via => :get, :as => :records_show

  scope '(home)' do
    controller :home do
      get '/' => :index

      get '/publish', :action => 'publish', :as => :home_publish
      match '/zizhi/daiban', :action => 'zizhi', :as => :zizhi_daiban
      match '/zizhi/zhuanrang', :action => 'zizhi'
      match '/zizhi/guakao', :action => 'zizhi'
    end
  end

  root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user && ( user.has_role :admin )
        can :access, :rails_admin
        can :dashboard
        can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/policy.rb
class Policy < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/record.rb
class Record < ActiveRecord::Base
  attr_accessible :details, :job_title, :locate_city, :locate_province, :price, :register_status, :title
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @news = News.all
    @policies = Policy.all
  end

  def show
    @record = Record.find(params[:id])
  end

  def region
  end

  def publish
    type_id = params[:type]
    if not type_id.nil?
      @type_id = type_id
    end
  end

  def zizhi
    @records = Record.all
  end

  def add
    @record = Record.new

    respond_to do |format|
      format.html # add.html.haml
    end
  end

  def create
    @record = Record.new(params[:record])

    respond_to do |format|
      if @record.save
        format.html { redirect_to zizhi_daiban_path, notice: t('.record_created_successfully.') }
        # format.json { render json: @maintain_invite_article, status: :created, location: @maintain_invite_article }
      else
        format.html { render action: "add" }
        # format.json { render json: @maintain_invite_article.errors, status: :unprocessable_entity }
      end
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/common/theme_jianzhu/_column_content_01.html.erb
<!--要闻发布/政治解读-->
<div class="center">
<!--要闻发布 开始-->
<div class="news_h">
  <div id="news_h_bt1"><a href="新闻-二级页.html"><img src="images/more_1.jpg" border="0" /></a></div>
  <!--循环 开始 显示5条-->
  <% news.each do |news| %>
    <div class="news_h_nrk">
      <div class="news_h_img"><a href="#"><img src="" alt="" name="" width="60" height="60" border="0" /></a></div>
      <div class="news_h_bt"><%= news.title %></div>
      <div class="news_h_day">[[<%= news.updated_at.strftime('%Y-%m-%d').to_s %>]]</div>
      <div class="news_h_nr"><a href="#" class="link_t2"><%= sanitize( truncate( news.content.html_safe, :length => 20, :omission => "..." ) ) %></a></div>
    </div>
  <% end %>
  <!--循环 结束 显示5条-->
</div>
<!--要闻发布 结束-->

<div class="left"><img src="images/tm.png" width="23" height="476" /></div>

<!--政治解读 开始-->
<div class="news_h">
  <div id="news_h_bt2"><a href="新闻-二级页.html"><img src="images/more_1.jpg" border="0" /></a></div>
  <!--循环 开始 显示5条-->
  <% policies.each do |policy| %>
    <div class="news_h_nrk">
      <div class="news_h_img"><a href="新闻-二级页-终页.html"><img src="" alt="" name="" width="60" height="60" border="0" /></a></div>
      <div class="news_h_bt"><%= policy.title %></div>
      <div class="news_h_day">[<%= policy.updated_at.strftime('%Y-%m-%d').to_s %>]</div>
      <div class="news_h_nr"><a href="新闻-二级页-终页.html" class="link_t2"><%= sanitize( truncate( policy.content.html_safe, :length => 20, :omission => "..." ) ) %></a></div>
    </div>
  <% end %>
  <!--循环 结束 显示5条-->
</div>
<!--政治解读 结束-->
</div>

app/views/common/theme_jianzhu/_column_content_advertising_01.html.erb
<div id="h_gg"><a href="#"><img src="" alt="" name="" width="999" height="80" border="0" /></a></div>

app/views/common/theme_jianzhu/_column_content_advertising_02.html.erb
<div id="h_fgg"><a href="#"><img src="" alt="" width="999" height="40" border="0" /></a></div>

app/views/common/theme_jianzhu/_column_content_information.html.erb
<div class="center">
  <!--按钮区域-->
  <div class="left"><a href="javascript:;" target="_top" onClick="showDiv('div_01', 'div_02', 'div_03', 'div_04', 'div_05')"><img src="images/home_zh/d_r1_c1.jpg" name="brtzsr1c2" width="119" height="53" border="0" id="Image1"></a></div>
  
  <div class="left"><a href="javascript:;" target="_top" onClick="showDiv('div_02', 'div_01', 'div_03', 'div_04', 'div_05')"><img src="images/home_zh/w_r1_c2.jpg" name="brtzsr1c2" width="90" height="53" border="0" id="Image2"></a></div>
  
  <div class="left"><a href="javascript:;" target="_top" onClick="showDiv('div_03', 'div_01', 'div_02', 'div_04', 'div_05')"><img src="images/home_zh/w_r1_c3.jpg" name="brtzsr1c2" width="85" height="53" border="0" id="Image3"></a></div>
  
  <div class="left"><a href="javascript:;" target="_top" onClick="showDiv('div_04', 'div_01', 'div_02', 'div_03', 'div_05')"><img src="images/home_zh/w_r1_c4.jpg" name="brtzsr1c2" width="85" height="53" border="0" id="Image4"></a></div>
  
  <div class="left"><a href="javascript:;" target="_top" onClick="showDiv('div_05', 'div_01', 'div_02', 'div_03', 'div_04')"><img src="images/home_zh/w_r1_c5.jpg" name="brtzsr1c2" width="85" height="53" border="0" id="Image5"></a></div>
  
  <div class="left"><img src="images/home_zh/btk.jpg" /></div>
  
  <!--展示区域-->
  <div id="h_zhk">
    <div id="div_01" style="display:''">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 11111...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  <div id="div_02" style="display:none">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 22222...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  <div id="div_03" style="display:none">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 33333...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  <div id="div_04" style="display:none">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 44444...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  <div id="div_05" style="display:none">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 55555...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  <div id="div_06" style="display:none">
  <!--循环开始 显示 15条-->
  <a href="#" class="zz_link_2">这里显示标题名称 66666...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 15条-->
  </div>
  </div>
</div>

app/views/common/theme_jianzhu/_column_content_segment.html.erb
<div class="center">
  <div id="zk_k1">
    <!--一级建造师-->
    <div id="zk_1">
  <ul>
    <li>
    <a href="#" class="zk_1bt">一级建造师</a>
    <a href="#" class="zk_1nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  <!--造价师-->
  <div id="zk_2">
  <ul>
    <li>
    <a href="#" class="zk_2bt">造价师</a>
    <a href="#" class="zk_1nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  <!--其他证书-->
  <div id="zk_3">
  <ul>
    <li>
    <a href="#" class="zk_3bt">其他证书</a>
    <a href="#" class="zk_1nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  </div>
  
  <div id="zk_k2">
  <div id="zk_k2_1">
    <!--二级建造师-->
    <div id="zk_4">
  <ul>
    <li>
    <a href="#" class="zk_4bt">二级建造师</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  <!--土木工程师-->
  <div id="zk_5">
  <ul>
    <li>
    <a href="#" class="zk_5bt">土木工程师</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  <!--监理师-->
  <div id="zk_6">
  <ul>
    <li>
    <a href="#" class="zk_5bt">监理师</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  </div>
  
  <div id="zk_k2_2">
    <!--公共设备工程师-->
    <div id="zk_7">
  <ul>
    <li>
    <a href="#" class="zk_6bt">公共设备工程师&nbsp;&nbsp;</a>
    <a href="#" class="zk_3nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
    <!--结构师-->
  <div id="zk_8">
  <ul>
    <li>
    <a href="#" class="zk_7bt">结构师</a>
    <a href="#" class="zk_3nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
    <!--职称证书-->
  <div id="zk_9">
  <ul>
    <li>
    <a href="#" class="zk_5bt">职称证书</a>
    <a href="#" class="zk_3nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  </div>
  
  <div id="zk_k2_3">
    <!--资质代办-->
    <div id="zk_10">
  <ul>
    <li>
    <a href="#" class="zk_8bt">资质代办</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>    </li>
  </ul>
  </div>
    <!--建筑师-->
  <div id="zk_11">
  <ul>
    <li>
    <a href="#" class="zk_5bt">建筑师</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
    <!--电气工程师-->
  <div id="zk_12">
  <ul>
    <li>
    <a href="#" class="zk_5bt">电气工程师</a>
    <a href="#" class="zk_2nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  </div>
  
  <div id="zk_k2_4">
    <!--建筑培训-->
    <div id="zk_13">
  <ul>
    <li>
    <a href="#" class="zk_5bt">建筑培训</a>
    <a href="#" class="zk_4nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  <!--注册咨询师-->
  <div id="zk_14">
  <ul>
    <li>
    <a href="#" class="zk_5bt">注册咨询师</a>
    <a href="#" class="zk_4nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
  </div>
  </div>
  <!--全职招聘求职-->
  <div id="zk_15">
    <ul>
    <li>
    <a href="#" class="zk_9bt">全职招聘求职</a>
    <a href="#" class="zk_4nr">这里显示分类(0)</a>
    </li>
  </ul>
  </div>
</div>

app/views/common/theme_jianzhu/_column_content_zizhi.html.erb
<div id="zzdb_bk">
  <div id="zzdb_bt">资质代办</div>
  <div id="zzdb_more"><a href="资质代办-资质信息.html"><img src="images/more_2.jpg" border="0" /></a></div>
</div>
<div id="zzdb_nrbk">
  <ul>
    <!--循环开始 显示24条-->
    <li><a href="资质代办三级页-公司信息.html" class="zz_link">这里显示标题名称...&nbsp;&nbsp;[12-11]</a></li>
  <!--循环结束 显示24条-->
  </ul>
</div>

app/views/common/theme_jianzhu/_column_foot.html.erb
<div id="foot_bk">
<div class="center">
  <!--友情链接-->
  <div id="yqlj">
    友情链接：
  <a href="#" class="link_3">标题名称</a>&nbsp;&nbsp;
  </div>
  <!--版权信息-->
  <div id="bqxx">
  <a href="#" class="link_3">推广服务</a>
  &nbsp;|&nbsp;
  <a href="#" class="link_3">联系我们</a>
  &nbsp;|&nbsp;
  <a href="#" class="link_3">关于我们</a>
  &nbsp;&nbsp;|&nbsp;&nbsp;
  <a href="#" class="link_3">网站公告</a>
  <br /><br />
  本站是一个建筑企业与人才交流的中立平台，用户发布的招聘求职信息与本站无关！<br />证书挂靠：010-82207151；资质办理升级：13522001640；咨询QQ：2776681109
  </div>
</div>
</div>

app/views/common/theme_jianzhu/_column_search_nav.html.erb
<!--搜索栏目-->
<div id="soo_bj">
  <form action="" method="get">
    <div class="center">
    <div id="soo_bk"><input name="textfield" type="text" class="soo_sr" value="搜索请输入关键字..." onFocus="this.value=''" /> </div>
    <div id="soo_anniu"><input name="" type="image" src="../images/soo_an_r1_c1.jpg" width="28" height="24" style="cursor:hand"/></div>
    <div id="fabu_anniu"><a href="<%= home_publish_url %>"><img src="../images/soo_an_r1_c3.jpg" border="0" /></a></div>
    <div id="tel_400">专家服务热线：400-029-3003</div>
    </div>
  </form>
</div>
<div class="center"><img src="<%= root_url %>/images/tm.png" width="1010" height="15" /></div>

<!--省份选择-->
<div id="sf_bk">
  <div id="sf_rk_1">
  <ul>
    <li><a href="#" class="sf_link">全国</a></li>
  <li><a href="#" class="sf_link">北京</a></li>
  <li><a href="#" class="sf_link">四川</a></li>
  <li><a href="#" class="sf_link">江苏</a></li>
  <li><a href="#" class="sf_link">上海</a></li>
  <li><a href="#" class="sf_link">广东</a></li>
  <li><a href="#" class="sf_link">山东</a></li>
  <li><a href="#" class="sf_link">河北</a></li>
  <li><a href="#" class="sf_link">浙江</a></li>
  <li><a href="#" class="sf_link">陕西</a></li>
  <li><a href="#" class="sf_link">安徽</a></li>
  <li><a href="#" class="sf_link">重庆</a></li>
  <li><a href="#" class="sf_link">湖北</a></li>
  <li><a href="#" class="sf_link">河南</a></li>
  <li><a href="#" class="sf_link">福建</a></li>
  <li><a href="#" class="sf_link">天津</a></li>
  <li><a href="#" class="sf_link">湖南</a></li>
  <li><a href="#" class="sf_link">山西</a></li>
  <li><a href="#" class="sf_link">江西</a></li>
  <li><a href="#" class="sf_link">广西</a></li>
  <li><a href="#" class="sf_link">辽宁</a></li>
  <li><a href="#" class="sf_link">贵州</a></li>
  <li><a href="#" class="sf_link">黑龙江</a></li>
  <li><a href="#" class="sf_link">云南</a></li>
  <li><a href="#" class="sf_link">甘肃</a></li>
  <li><a href="#" class="sf_link">吉林</a></li>
  <li><a href="#" class="sf_link">内蒙古</a></li>
  <li><a href="#" class="sf_link">青海</a></li>
  <li><a href="#" class="sf_link">海南</a></li>
  <li><a href="#" class="sf_link">宁夏</a></li>
  <li><a href="#" class="sf_link">新疆</a></li>
  <li><a href="#" class="sf_link">西藏</a></li>
  </ul>
  </div>
  
  <div id="sf_rk_2">
  <a href="#" class="link_t1">企业航母号上线通 ></a><br />
  <a href="#" class="link_t1">网站发布的个人挂 ></a>
  </div>
</div>

app/views/common/theme_jianzhu/_column_useful_links.html.erb
<div class="center"><img src="images/cywz_r1_c1.jpg" /></div>
<div id="cywz">
  <!--循环开始 显示 9条-->
  <a href="#" class="zz_link_3">这里显示标题名称...&nbsp;&nbsp;[12-11]</a>
  <!--循环结束 显示 9条-->
</div>
<div class="center"><img src="images/tm.png" width="100%" height="15" /></div>

app/views/common/theme_jianzhu/_top_bar.html.erb
<div id="top_bjs">
  <div class="center">
    <div class="top_nr"><a href="<%= root_url %>" class="link_1">【全国】</a></div>
  <div class="top_nr">[
    <a href="#" class="link_2">切换城市</a>&nbsp;
    <a href="#" class="link_2">北京</a>&nbsp;
    <a href="#" class="link_2">天津</a>&nbsp;
    <a href="#" class="link_2">上海</a>&nbsp;
    <a href="#" class="link_2">深圳</a>&nbsp;
    <a href="#" class="link_2">山东</a>]
  </div>
  <div id="top_nr_2">
    <% if !current_user %>
      <a href="<%= new_user_session_path %>" class="link_2">会员登录</a>&nbsp;&nbsp;
      <a href="<%= new_user_registration_path %>" class="link_2">免费注册</a>&nbsp;&nbsp;
    <% else %>
      <a href="#" class="link_2">
        <%= current_user.email %>
      </a>&nbsp;&nbsp;
      <%= link_to '退出', destroy_user_session_path, { method: :delete, class: 'link_2'} %>
    <% end %>
    <a href="<%= home_publish_url %>" class="link_2">发布</a>&nbsp;&nbsp; </div>
  <div class="left"><a href="创建简历_1.html" class="top_jl">创建我的简历</a></div>
  </div>
</div>

app/views/common/theme_jianzhu/_top_nav.html.erb
<!--LOGO-->
<div class="center"><img src="<%= root_url %>/images/h-logo.jpg" /></div>
<!--导航-->
<div id="link_box">
  <ul>
  <li><a href="<%= root_url %>" class="link_dh">首 页</a></li>
  <li><a href="<%= zizhi_daiban_path %>" class="link_dh">资质代办</a></li>
  <li><a href="<%= zizhi_daiban_path %>" class="link_dh">资质转让</a></li>
  <li><a href="<%= zizhi_daiban_path %>" class="link_dh">资质挂靠</a></li>
  <li><a href="人员挂靠=已验证简历.html" class="link_dh">人员挂靠</a></li>
  <li><a href="公司黄页-资质公司.html" class="link_dh">公司黄页</a></li>
  <li><a href="建筑培训-建筑培训.html" class="link_dh">建筑培训</a></li>
  <li><a href="招聘求职-招聘.html" class="link_dh">企业招聘</a></li>
  <li><a href="#" class="link_dh">资质查询</a></li>
  </ul>
</div>

app/views/home/add.html.haml
= render partial: 'home/publish_templates/content_add'

app/views/home/publish.html.haml
- if not @type_id
  = render partial: 'home/publish_templates/content_type'

- if @type_id
  - if @type_id = 1
    = render partial: 'home/publish_templates/content_type_01'

app/views/home/publish_templates/_content_add.html.erb
<!--内容开始-->
<div class="center"><img src="<%= root_url %>images/release/bt_3.jpg" width="1010" height="78" /></div>
<div class="center">
  <div id="member">
  <div class="left"><img src="<%= root_url %>images/tm.png" width="963" height="36" /></div>
  <div class="left">
    <%= form_for :record, :url => home_records_path do |f| %>
      <table width="964" height="323" border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td width="125" height="45" align="right" class="txt_4"><span class="txt_2">*</span> 标题：</td>
          <td width="566" height="45">
            <input name="record[title]" type="text" class="fb3_sr" />            
          </td>
          <td width="273" rowspan="5"><input name="" type="image" src="<%= root_url %>images/release/fabu.jpg" width="153" height="41" /></td>
        </tr>
        <tr>
          <td height="45" align="right" class="txt_4"><span class="txt_2">*</span> 证书所在地：</td>
        <td height="45">
      <select name="record[locate_province]" class="txt_1">
            <option value="无">请选择省份</option>
            <option value="安徽">A 安徽</option>
            <option value="北京">B 北京</option>
            <option value="重庆">C 重庆</option>
            <option value="福建">F 福建</option>
            <option value="广东">G 广东</option>
            <option value="广西">G 广西</option>
            <option value="甘肃">G 甘肃</option>
            <option value="贵州">G 贵州</option>
            <option value="河北">H 河北</option>
            <option value="河南">H 河南</option>
            <option value="海南">H 海南</option>
            <option value="湖北">H 湖北</option>
            <option value="湖南">H 湖南</option>
            <option value="黑龙江">H 黑龙江</option>
            <option value="吉林">J 吉林</option>
            <option value="江苏">J 江苏</option>
            <option value="江西">J 江西</option>
            <option value="辽宁">L 辽宁</option>
            <option value="内蒙古">N 内蒙古</option>
            <option value="宁夏">N 宁夏</option>
            <option value="青海">Q 青海</option>
            <option value="上海">S 上海</option>
            <option value="四川">S 四川</option>
            <option value="山东">S 山东</option>
            <option value="山西">S 山西</option>
            <option value="陕西">S 陕西</option>
            <option value="天津">T 天津</option>
            <option value="新疆">X 新疆</option>
            <option value="西藏">X 西藏</option>
            <option value="云南">Y 云南</option>
            <option value="浙江">Z 浙江</option>
          </select>
      
          <select name="record[locate_city]" class="txt_1">
            <option value="">请选择城市</option>
          </select>
    </td>
          </tr>
        <tr>
          <td height="45" align="right" class="txt_4"><span class="txt_2">*</span> 注册情况：</td>
          <td height="45" class="txt_4"><input type="radio" name="record[register_status]" value="初始注册" />
            初始注册
              <input type="radio" name="record[register_status]" value="转注册" />
            转注册</td>
          </tr>
        <tr>
          <td height="45" align="right" class="txt_4">挂靠价格：</td>
          <td height="45" class="txt_4">
      <select name="record[price]" class="txt_1">
            <option value="" selected="selected">面议</option>
      <option value="1万元以下">1万元以下</option>
      <option value="1-2万元">1-2万元</option>
      <option value="2-3万元">2-3万元</option>
      <option value="3-5万元">3-5万元</option>
      <option value="5-10万元">5-10万元</option>
      <option value="10-15万元">10-15万元</option>
      <option value="15万元以上">15万元以上</option>
      </select>
            职称：
            <select name="record[job_title]" class="txt_1">
              <option value="">没有</option>
      </select>
      </td>
          </tr>
        <tr>
          <td align="right" class="txt_4"><span class="txt_2">*</span> 详细说明：</td>
          <td><textarea name="record[details]" class="fb3_sr2"></textarea></td>
          </tr>
      </table>
    <% end %>  
  </div>
  </div>
</div>
<div class="center"><img src="<%= root_url %>images/release/fgx_r2_c1.jpg" width="1010" height="25" /></div>

app/views/home/publish_templates/_content_type.html.erb
<!--内容开始-->
<div class="center"><img src="<%= root_url %>/images/release/bt_1.jpg" width="1010" height="78" /></div>
<div class="center">
  <div id="member">
    <div class="member_k">
    <p><span class="txt_3">个 人</span></p>
    <a href="<%= home_publish_path %>/1" class="fabu_txt">- 个人挂证</a><br />
    <a href="<%= home_publish_path %>/2" class="fabu_txt">- 全职简历</a>    </div>
    <div class="left"><img src="<%= root_url %>/images/release/fgx_r1_c2.jpg" /></div>
  
    <div class="member_k">
    <p><span class="txt_3">企 业</span></p>
    <a href="<%= home_publish_path %>/3" class="fabu_txt">- 企业聘证</a><br />
    <a href="<%= home_publish_path %>/4" class="fabu_txt">- 全职招聘</a>    </div>
  <div class="left"><img src="<%= root_url %>/images/release/fgx_r1_c2.jpg" /></div>
  
    <div class="member_k">
    <p><span class="txt_3">猎 头</span></p>
    <a href="<%= home_publish_path %>/5" class="fabu_txt">- 猎头聘证</a><br />
    <a href="<%= home_publish_path %>/6" class="fabu_txt">- 猎头挂证</a><br />
    <a href="<%= home_publish_path %>/7" class="fabu_txt">- 全职招聘</a><br />
    <a href="<%= home_publish_path %>/8" class="fabu_txt">- 培训信息</a><br />
    <a href="<%= home_publish_path %>/9" class="fabu_txt">- 资质代办(新版)</a><br />
    <a href="<%= home_publish_path %>/10" class="fabu_txt">- 资质代办(旧版)</a>    </div>
  </div>
</div>
<div class="center"><img src="<%= root_url %>/images/release/fgx_r2_c1.jpg" width="1010" height="25" /></div>

app/views/home/publish_templates/_content_type_01.html.erb
<!--内容开始-->
<div class="center"><img src="../images/release/bt_2.jpg" width="1010" height="78" /></div>
<div class="center">
  <!--选择分类-循环开始-->
  <div class="fb_b1">这里显示大标题名称</div>
  <div class="fb_b2">
    <ul>
      <!--小类循环 开始-->
      <li><a href="<%= home_publish_add_url %>" class="fb_an">小标题名称</a></li>
      <!--小类循环 结束-->
    </ul>
  </div>
  <!--选择分类-循环结束-->
</div>
<div class="center"><img src="../images/jianli/bk_1_r4_c1.jpg" /></div>

app/views/home/region.html.haml
%h1 Home#region
%p Find me in app/views/home/region.html.haml

app/views/home/show.html.haml
= render partial: 'home/show_templates/view_content'

app/views/home/zizhi.html.haml
= render partial: 'home/zizhi_templates/content'